version: "3"
services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?dbautoReconnect=true&failOverReadOnly=false&maxReconnects=10
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - local
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

networks:
  local: